#ifndef ISR_H
#define ISR_H

// #include <stdint.h>
// #include <stddef.h>
// #include <stdbool.h>

// #include "state.h"
// #include "util.h"
// #include "idt.h"
// #include "../drivers/keyboard.h"

// /* ISRs reserved for CPU exceptions */
// extern void isr0();
// extern void isr1();
// extern void isr2();
// extern void isr3();
// extern void isr4();
// extern void isr5();
// extern void isr6();
// extern void isr7();
// extern void isr8();
// extern void isr9();
// extern void isr10();
// extern void isr11();
// extern void isr12();
// extern void isr13();
// extern void isr14();
// extern void isr15();
// extern void isr16();
// extern void isr17();
// extern void isr18();
// extern void isr19();
// extern void isr20();
// extern void isr21();
// extern void isr22();
// extern void isr23();
// extern void isr24();
// extern void isr25();
// extern void isr26();
// extern void isr27();
// extern void isr28();
// extern void isr29();
// extern void isr30();
// extern void isr31();

// /* IRQ definitions */
// extern void irq0();
// extern void irq1();
// extern void irq2();
// extern void irq3();
// extern void irq4();
// extern void irq5();
// extern void irq6();
// extern void irq7();
// extern void irq8();
// extern void irq9();
// extern void irq10();
// extern void irq11();
// extern void irq12();
// extern void irq13();
// extern void irq14();
// extern void irq15();

// #define IRQ0 32
// #define IRQ1 33
// #define IRQ2 34
// #define IRQ3 35
// #define IRQ4 36
// #define IRQ5 37
// #define IRQ6 38
// #define IRQ7 39
// #define IRQ8 40
// #define IRQ9 41
// #define IRQ10 42
// #define IRQ11 43
// #define IRQ12 44
// #define IRQ13 45
// #define IRQ14 46
// #define IRQ15 47

// extern void isr48();
// extern void isr49();
// extern void isr50();
// extern void isr51();
// extern void isr52();
// extern void isr53();
// extern void isr54();
// extern void isr55();
// extern void isr56();
// extern void isr57();
// extern void isr58();
// extern void isr59();
// extern void isr60();
// extern void isr61();
// extern void isr62();
// extern void isr63();
// extern void isr64();
// extern void isr65();
// extern void isr66();
// extern void isr67();
// extern void isr68();
// extern void isr69();
// extern void isr70();
// extern void isr71();
// extern void isr72();
// extern void isr73();
// extern void isr74();
// extern void isr75();
// extern void isr76();
// extern void isr77();
// extern void isr78();
// extern void isr79();
// extern void isr80();
// extern void isr81();
// extern void isr82();
// extern void isr83();
// extern void isr84();
// extern void isr85();
// extern void isr86();
// extern void isr87();
// extern void isr88();
// extern void isr89();
// extern void isr90();
// extern void isr91();
// extern void isr92();
// extern void isr93();
// extern void isr94();
// extern void isr95();
// extern void isr96();
// extern void isr97();
// extern void isr98();
// extern void isr99();
// extern void isr100();
// extern void isr101();
// extern void isr102();
// extern void isr103();
// extern void isr104();
// extern void isr105();
// extern void isr106();
// extern void isr107();
// extern void isr108();
// extern void isr109();
// extern void isr110();
// extern void isr111();
// extern void isr112();
// extern void isr113();
// extern void isr114();
// extern void isr115();
// extern void isr116();
// extern void isr117();
// extern void isr118();
// extern void isr119();
// extern void isr120();
// extern void isr121();
// extern void isr122();
// extern void isr123();
// extern void isr124();
// extern void isr125();
// extern void isr126();
// extern void isr127();
// extern void isr128();
// extern void isr129();
// extern void isr130();
// extern void isr131();
// extern void isr132();
// extern void isr133();
// extern void isr134();
// extern void isr135();
// extern void isr136();
// extern void isr137();
// extern void isr138();
// extern void isr139();
// extern void isr140();
// extern void isr141();
// extern void isr142();
// extern void isr143();
// extern void isr144();
// extern void isr145();
// extern void isr146();
// extern void isr147();
// extern void isr148();
// extern void isr149();
// extern void isr150();
// extern void isr151();
// extern void isr152();
// extern void isr153();
// extern void isr154();
// extern void isr155();
// extern void isr156();
// extern void isr157();
// extern void isr158();
// extern void isr159();
// extern void isr160();
// extern void isr161();
// extern void isr162();
// extern void isr163();
// extern void isr164();
// extern void isr165();
// extern void isr166();
// extern void isr167();
// extern void isr168();
// extern void isr169();
// extern void isr170();
// extern void isr171();
// extern void isr172();
// extern void isr173();
// extern void isr174();
// extern void isr175();
// extern void isr176();
// extern void isr177();
// extern void isr178();
// extern void isr179();
// extern void isr180();
// extern void isr181();
// extern void isr182();
// extern void isr183();
// extern void isr184();
// extern void isr185();
// extern void isr186();
// extern void isr187();
// extern void isr188();
// extern void isr189();
// extern void isr190();
// extern void isr191();
// extern void isr192();
// extern void isr193();
// extern void isr194();
// extern void isr195();
// extern void isr196();
// extern void isr197();
// extern void isr198();
// extern void isr199();
// extern void isr200();
// extern void isr201();
// extern void isr202();
// extern void isr203();
// extern void isr204();
// extern void isr205();
// extern void isr206();
// extern void isr207();
// extern void isr208();
// extern void isr209();
// extern void isr210();
// extern void isr211();
// extern void isr212();
// extern void isr213();
// extern void isr214();
// extern void isr215();
// extern void isr216();
// extern void isr217();
// extern void isr218();
// extern void isr219();
// extern void isr220();
// extern void isr221();
// extern void isr222();
// extern void isr223();
// extern void isr224();
// extern void isr225();
// extern void isr226();
// extern void isr227();
// extern void isr228();
// extern void isr229();
// extern void isr230();
// extern void isr231();
// extern void isr232();
// extern void isr233();
// extern void isr234();
// extern void isr235();
// extern void isr236();
// extern void isr237();
// extern void isr238();
// extern void isr239();
// extern void isr240();
// extern void isr241();
// extern void isr242();
// extern void isr243();
// extern void isr244();
// extern void isr245();
// extern void isr246();
// extern void isr247();
// extern void isr248();
// extern void isr249();
// extern void isr250();
// extern void isr251();
// extern void isr252();
// extern void isr253();
// extern void isr254();
// extern void isr255();


// typedef void (*state_t)(cpu_state*);

// extern void irq_handler(cpu_state* state);
// extern void isr_handler(cpu_state* state);
// void register_interrupt_handler(uint8_t n, state_t handler);
// void isr_install();
// void irq_install();

void interrupt_handler_0();
void interrupt_handler_1();
void interrupt_handler_2();
void interrupt_handler_3();
void interrupt_handler_4();
void interrupt_handler_5();
void interrupt_handler_6();
void interrupt_handler_7();
void interrupt_handler_8();
void interrupt_handler_9();
void interrupt_handler_10();
void interrupt_handler_11();
void interrupt_handler_12();
void interrupt_handler_13();
void interrupt_handler_14();
void interrupt_handler_15();
void interrupt_handler_16();
void interrupt_handler_17();
void interrupt_handler_18();
void interrupt_handler_19();
void interrupt_handler_20();
void interrupt_handler_21();
void interrupt_handler_22();
void interrupt_handler_23();
void interrupt_handler_24();
void interrupt_handler_25();
void interrupt_handler_26();
void interrupt_handler_27();
void interrupt_handler_28();
void interrupt_handler_29();
void interrupt_handler_30();
void interrupt_handler_31();
void interrupt_handler_32();
void interrupt_handler_33();
void interrupt_handler_34();
void interrupt_handler_35();
void interrupt_handler_36();
void interrupt_handler_37();
void interrupt_handler_38();
void interrupt_handler_39();
void interrupt_handler_40();
void interrupt_handler_41();
void interrupt_handler_42();
void interrupt_handler_43();
void interrupt_handler_44();
void interrupt_handler_45();
void interrupt_handler_46();
void interrupt_handler_47();
void interrupt_handler_48();
void interrupt_handler_49();
void interrupt_handler_50();
void interrupt_handler_51();
void interrupt_handler_52();
void interrupt_handler_53();
void interrupt_handler_54();
void interrupt_handler_55();
void interrupt_handler_56();
void interrupt_handler_57();
void interrupt_handler_58();
void interrupt_handler_59();
void interrupt_handler_60();
void interrupt_handler_61();
void interrupt_handler_62();
void interrupt_handler_63();
void interrupt_handler_64();
void interrupt_handler_65();
void interrupt_handler_66();
void interrupt_handler_67();
void interrupt_handler_68();
void interrupt_handler_69();
void interrupt_handler_70();
void interrupt_handler_71();
void interrupt_handler_72();
void interrupt_handler_73();
void interrupt_handler_74();
void interrupt_handler_75();
void interrupt_handler_76();
void interrupt_handler_77();
void interrupt_handler_78();
void interrupt_handler_79();
void interrupt_handler_80();
void interrupt_handler_81();
void interrupt_handler_82();
void interrupt_handler_83();
void interrupt_handler_84();
void interrupt_handler_85();
void interrupt_handler_86();
void interrupt_handler_87();
void interrupt_handler_88();
void interrupt_handler_89();
void interrupt_handler_90();
void interrupt_handler_91();
void interrupt_handler_92();
void interrupt_handler_93();
void interrupt_handler_94();
void interrupt_handler_95();
void interrupt_handler_96();
void interrupt_handler_97();
void interrupt_handler_98();
void interrupt_handler_99();
void interrupt_handler_100();
void interrupt_handler_101();
void interrupt_handler_102();
void interrupt_handler_103();
void interrupt_handler_104();
void interrupt_handler_105();
void interrupt_handler_106();
void interrupt_handler_107();
void interrupt_handler_108();
void interrupt_handler_109();
void interrupt_handler_110();
void interrupt_handler_111();
void interrupt_handler_112();
void interrupt_handler_113();
void interrupt_handler_114();
void interrupt_handler_115();
void interrupt_handler_116();
void interrupt_handler_117();
void interrupt_handler_118();
void interrupt_handler_119();
void interrupt_handler_120();
void interrupt_handler_121();
void interrupt_handler_122();
void interrupt_handler_123();
void interrupt_handler_124();
void interrupt_handler_125();
void interrupt_handler_126();
void interrupt_handler_127();
void interrupt_handler_128();
void interrupt_handler_129();
void interrupt_handler_130();
void interrupt_handler_131();
void interrupt_handler_132();
void interrupt_handler_133();
void interrupt_handler_134();
void interrupt_handler_135();
void interrupt_handler_136();
void interrupt_handler_137();
void interrupt_handler_138();
void interrupt_handler_139();
void interrupt_handler_140();
void interrupt_handler_141();
void interrupt_handler_142();
void interrupt_handler_143();
void interrupt_handler_144();
void interrupt_handler_145();
void interrupt_handler_146();
void interrupt_handler_147();
void interrupt_handler_148();
void interrupt_handler_149();
void interrupt_handler_150();
void interrupt_handler_151();
void interrupt_handler_152();
void interrupt_handler_153();
void interrupt_handler_154();
void interrupt_handler_155();
void interrupt_handler_156();
void interrupt_handler_157();
void interrupt_handler_158();
void interrupt_handler_159();
void interrupt_handler_160();
void interrupt_handler_161();
void interrupt_handler_162();
void interrupt_handler_163();
void interrupt_handler_164();
void interrupt_handler_165();
void interrupt_handler_166();
void interrupt_handler_167();
void interrupt_handler_168();
void interrupt_handler_169();
void interrupt_handler_170();
void interrupt_handler_171();
void interrupt_handler_172();
void interrupt_handler_173();
void interrupt_handler_174();
void interrupt_handler_175();
void interrupt_handler_176();
void interrupt_handler_177();
void interrupt_handler_178();
void interrupt_handler_179();
void interrupt_handler_180();
void interrupt_handler_181();
void interrupt_handler_182();
void interrupt_handler_183();
void interrupt_handler_184();
void interrupt_handler_185();
void interrupt_handler_186();
void interrupt_handler_187();
void interrupt_handler_188();
void interrupt_handler_189();
void interrupt_handler_190();
void interrupt_handler_191();
void interrupt_handler_192();
void interrupt_handler_193();
void interrupt_handler_194();
void interrupt_handler_195();
void interrupt_handler_196();
void interrupt_handler_197();
void interrupt_handler_198();
void interrupt_handler_199();
void interrupt_handler_200();
void interrupt_handler_201();
void interrupt_handler_202();
void interrupt_handler_203();
void interrupt_handler_204();
void interrupt_handler_205();
void interrupt_handler_206();
void interrupt_handler_207();
void interrupt_handler_208();
void interrupt_handler_209();
void interrupt_handler_210();
void interrupt_handler_211();
void interrupt_handler_212();
void interrupt_handler_213();
void interrupt_handler_214();
void interrupt_handler_215();
void interrupt_handler_216();
void interrupt_handler_217();
void interrupt_handler_218();
void interrupt_handler_219();
void interrupt_handler_220();
void interrupt_handler_221();
void interrupt_handler_222();
void interrupt_handler_223();
void interrupt_handler_224();
void interrupt_handler_225();
void interrupt_handler_226();
void interrupt_handler_227();
void interrupt_handler_228();
void interrupt_handler_229();
void interrupt_handler_230();
void interrupt_handler_231();
void interrupt_handler_232();
void interrupt_handler_233();
void interrupt_handler_234();
void interrupt_handler_235();
void interrupt_handler_236();
void interrupt_handler_237();
void interrupt_handler_238();
void interrupt_handler_239();
void interrupt_handler_240();
void interrupt_handler_241();
void interrupt_handler_242();
void interrupt_handler_243();
void interrupt_handler_244();
void interrupt_handler_245();
void interrupt_handler_246();
void interrupt_handler_247();
void interrupt_handler_248();
void interrupt_handler_249();
void interrupt_handler_250();
void interrupt_handler_251();
void interrupt_handler_252();
void interrupt_handler_253();
void interrupt_handler_254();
void interrupt_handler_255();


struct cpu_statez {
  uint32_t cr2;
  uint32_t ebp;
  uint32_t edi;
  uint32_t esi;
  uint32_t edx;
  uint32_t ecx;
  uint32_t ebx;
  uint32_t eax;
} __attribute__((packed));

void enable_keyboard_interrupts();
void interrupt_handler(struct cpu_statez cpu, uint32_t interrupt_number, uint32_t error_code, uint32_t eip);


#endif
